# Generated by Django 4.2.7 on 2025-11-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reviews/%Y/%m/', verbose_name='Изображение')),
                ('alt_text', models.CharField(max_length=255, verbose_name='Alt текст')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('caption', models.TextField(blank=True, verbose_name='Подпись')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'review',
                'ordering': ('sort_order', '-id'),
            },
        ),
    ]
