# Generated by Django 4.2.7 on 2025-08-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание'),
        ),
    ]
