# Generated by Django 4.2.7 on 2025-08-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_products_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание'),
        ),
    ]
