# Generated by Django 4.2.7 on 2025-08-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_categories_short_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='categories',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=100, verbose_name='Порядок'),
        ),
    ]
