# Generated by Django 4.2.7 on 2025-08-25 17:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_alter_categories_options_categories_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
