# Generated by Django 5.2.1 on 2025-09-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_categories_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/cards/', verbose_name='Изображение для карточки'),
        ),
    ]
