# Generated by Django 5.2.1 on 2025-09-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_products_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='gift_enabled',
            field=models.BooleanField(default=False, verbose_name='Подарок на выбор (отпечаток)'),
        ),
    ]
