# Generated by Django 5.2.1 on 2025-10-14 07:42

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_products_gift_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='description_ru',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание (RU)'),
        ),
        migrations.AddField(
            model_name='categories',
            name='name_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название (RU)'),
        ),
        migrations.AddField(
            model_name='categories',
            name='seo_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories_seo', verbose_name='SEO-изображение'),
        ),
        migrations.AddField(
            model_name='categories',
            name='short_description_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание (RU)'),
        ),
        migrations.AddField(
            model_name='products',
            name='description_ru',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание (RU)'),
        ),
        migrations.AddField(
            model_name='products',
            name='gift_double',
            field=models.BooleanField(default=False, verbose_name='Два стрейна (гроубокс)'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название (RU)'),
        ),
        migrations.AddField(
            model_name='products',
            name='short_description_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание (RU)'),
        ),
        migrations.AddField(
            model_name='products',
            name='species',
            field=models.CharField(blank=True, choices=[('cubensis', 'Cubensis'), ('panaeolus', 'Panaeolus')], default='', max_length=20, verbose_name='Вид (species)'),
        ),
    ]
