# Generated by Django 5.2.1 on 2025-10-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_add_gift_double_if_missing'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_benefit',
            field=models.BooleanField(default=False, verbose_name='Выгода'),
        ),
        migrations.AlterField(
            model_name='products',
            name='gift_double',
            field=models.BooleanField(default=False, verbose_name='Два стрейна'),
        ),
        migrations.AlterField(
            model_name='products',
            name='gift_enabled',
            field=models.BooleanField(default=False, verbose_name='Выбор стрейна'),
        ),
    ]
