# Generated by Django 5.2.1 on 2025-10-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_categories_created_at_categories_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='categories',
            name='meta_description_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Meta description (RU)'),
        ),
    ]
