# Generated by Django 5.2.1 on 2025-10-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0015_categories_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='categories',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta title (RU)'),
        ),
    ]
