# Generated by Django 5.2.1 on 2025-11-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_categories_meta_title_categories_meta_title_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_unique',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Уникальное предложение'),
        ),
    ]
