# Generated by Django 5.2.1 on 2025-11-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0017_products_is_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={},
        ),
        migrations.AlterField(
            model_name='categories',
            name='short_description',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='short_description_ru',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Краткое описание (RU)'),
        ),
    ]
