# Generated by Django 5.2.1 on 2025-11-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0018_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='short_description',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='products',
            name='short_description_ru',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Краткое описание (RU)'),
        ),
    ]
