# Generated by Django 4.2.7 on 2025-11-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0019_alter_products_short_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('sort_order', '-id'), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='products',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=100, verbose_name='Порядок'),
        ),
    ]
