# Generated by Django 5.2.1 on 2025-11-03 16:24

import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uk', models.CharField(max_length=200, verbose_name='Назва (укр)')),
                ('name_ru', models.CharField(blank=True, default='', max_length=200, verbose_name='Название (рус)')),
                ('slug', models.SlugField(unique=True)),
                ('description_uk', models.TextField(blank=True, default='', verbose_name='Опис (укр)')),
                ('description_ru', models.TextField(blank=True, default='', verbose_name='Описание (рус)')),
            ],
            options={
                'verbose_name': 'Категория статьи',
                'verbose_name_plural': 'Категории статей',
                'ordering': ('name_uk',),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(max_length=255, verbose_name='Заголовок (укр)')),
                ('title_ru', models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок (рус)')),
                ('slug', models.SlugField(help_text='URL без дат: /articles/<slug>/', unique=True)),
                ('excerpt_uk', models.CharField(blank=True, default='', max_length=300, verbose_name='Краткое описание (укр)')),
                ('excerpt_ru', models.CharField(blank=True, default='', max_length=300, verbose_name='Краткое описание (рус)')),
                ('body_uk', tinymce.models.HTMLField(verbose_name='Текст (укр)')),
                ('body_ru', tinymce.models.HTMLField(blank=True, default='', verbose_name='Текст (рус)')),
                ('cover_image', models.ImageField(upload_to='articles/covers/', verbose_name='Обложка')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=10)),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title_uk', models.CharField(blank=True, default='', max_length=255)),
                ('meta_title_ru', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description_uk', models.CharField(blank=True, default='', max_length=300)),
                ('meta_description_ru', models.CharField(blank=True, default='', max_length=300)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, related_name='articles', to='articles.articlecategory')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ('-published_at', '-id'),
                'indexes': [models.Index(fields=['status', 'published_at'], name='articles_ar_status_7759bd_idx')],
            },
        ),
    ]
