# Generated by Django 5.2.1 on 2025-11-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_caption_ru',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Подпись к обложке (рус)'),
        ),
        migrations.AddField(
            model_name='article',
            name='cover_caption_uk',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Подпись к обложке (укр)'),
        ),
    ]
