# Generated by Django 5.2.1 on 2025-09-22 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0010_products_gift_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('gift_choice', models.CharField(blank=True, default='', max_length=255, verbose_name='Подарок (отпечаток)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.products', verbose_name='Товар')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзина',
                'db_table': 'cart',
                'ordering': ('id',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('user', None), _negated=True), fields=('user', 'product', 'gift_choice'), name='uniq_user_product_gift'), models.UniqueConstraint(condition=models.Q(('session_key', None), _negated=True), fields=('session_key', 'product', 'gift_choice'), name='uniq_session_product_gift')],
            },
        ),
    ]
