# Generated by Django 4.2.7 on 2025-08-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('label', models.CharField(blank=True, max_length=128, verbose_name='Метка/ссылка (короткая)')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка')),
                ('subtitle', models.TextField(blank=True, verbose_name='Подзаголовок / краткое описание')),
                ('image', models.ImageField(upload_to='promos/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Показывать с')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Показывать до')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Промо/новость',
                'verbose_name_plural': 'Промо/новости',
                'ordering': ['order', '-created'],
            },
        ),
    ]
