# Generated by Django 4.2.7 on 2025-08-23 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promo',
        ),
    ]
